<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-H0PI4DT" failures="1" tests="1" name="Default test(failed)" time="0.102" errors="0" timestamp="2022-09-19T16:56:45 IST">
  <testcase classname="retryExample.AmazonTest" name="payment" time="0.022">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at retryExample.AmazonTest.payment(AmazonTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- payment -->
  <testcase classname="retryExample.AmazonTest" name="verifyAppTitle" time="0.0">
    <ignored/>
  </testcase> <!-- verifyAppTitle -->
  <testcase classname="retryExample.AmazonTest" name="addItems" time="0.0">
    <ignored/>
  </testcase> <!-- addItems -->
  <testcase classname="retryExample.AmazonTest" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
</testsuite> <!-- Default test(failed) -->
